### ISSUE TITLE
关于python内置的hash函数

### ISSUE THREAD

**Issue by Xisaname** [Xisaname/Group4-back-end#8]
我们进行了登录注册功能的开发，在开发过程中，为了保证用户隐私安全，我们计划将用户密码的哈希值存储到数据库中，但在使用python内置的hash函数之后，我们在测试时出现错误，经过debug发现，同一次运行时对于同一字符串进行hash得到的哈希值是相同的，但是当再次运行项目时，同一字符串却得到了不同的哈希值。经过查资料我们发现：这是由于Python的字符串hash算法有一个启动时随机生成secret prefix/suffix的机制，存在随机化现象：对同一个字符串输入，不同解释器进程得到的hash结果可能不同。因此当需要做可重现可跨进程保持一致性的hash，需要用到hashlib模块。因此我们改用了MD5进行加密。

**Comment by SadPencil** [comment]
MD5等哈希算法是摘要，不是加密
